In [25]:
import pandas as pd
import numpy as np
import math

In [26]:
df_pitch_subs = pd.read_csv('pitching_subs.csv')
df_pitch_subs.head()

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,OUTS_CT,AWAY_SCORE_CT,HOME_SCORE_CT,onFirst,onSecond,onThird,SAVE_PIT_ID
0,ANA201004050,jepsk001,7,0,0,3,4,0,0,0,fuenb001
1,ANA201004050,rodnf001,8,0,0,3,4,0,0,0,fuenb001
2,ANA201004050,fuenb001,9,0,0,3,6,0,0,0,fuenb001
3,ANA201004050,craij001,5,1,2,3,4,1,0,1,fuenb001
4,ANA201004050,mijaj001,7,1,1,3,4,0,0,0,fuenb001

In [27]:
def save_sit(row):
    if row['BAT_HOME_ID'] == 0 and row['HOME_SCORE_CT'] > row['AWAY_SCORE_CT']:
        return True
    elif row['BAT_HOME_ID'] == 1 and row['HOME_SCORE_CT'] < row['AWAY_SCORE_CT']:
        return True
    else:
        return False

df_pitch_subs['SAVE_SIT'] = df_pitch_subs.apply(save_sit, axis=1)

In [28]:
df_pitch_subs[['GAME_ID', 'PIT_ID', 'INN_CT', 'BAT_HOME_ID', 'AWAY_SCORE_CT', 'HOME_SCORE_CT', 'SAVE_PIT_ID', 'SAVE_SIT']].head(100)

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,AWAY_SCORE_CT,HOME_SCORE_CT,SAVE_PIT_ID,SAVE_SIT
0,ANA201004050,jepsk001,7,0,3,4,fuenb001,True
1,ANA201004050,rodnf001,8,0,3,4,fuenb001,True
2,ANA201004050,fuenb001,9,0,3,6,fuenb001,True
3,ANA201004050,craij001,5,1,3,4,fuenb001,False
4,ANA201004050,mijaj001,7,1,3,4,fuenb001,False
5,ANA201004050,neshp001,8,1,3,6,fuenb001,False
6,ANA201004060,palmm001,6,0,5,3,raucj001,False
7,ANA201004060,stokb001,8,0,5,3,raucj001,False
8,ANA201004060,duenb001,7,1,5,3,raucj001,True
9,ANA201004060,guerm001,8,1,5,3,raucj001,True
10,ANA201004060,raucj001,9,1,5,3,raucj001,True
11,ANA201004070,bulgj001,7,0,4,1,raucj001,False
12,ANA201004070,shies002,9,0,4,1,raucj001,False
13,ANA201004070,guerm001,8,1,4,1,raucj001,True
14,ANA201004070,raucj001,9,1,4,1,raucj001,True
15,ANA201004080,jepsk001,7,0,3,1,None,False
16,ANA201004080,stokb001,8,0,3,1,None,False
17,ANA201004080,rodnf001,9,0,6,1,None,False
18,ANA201004080,neshp001,6,1,3,1,None,True
19,ANA201004080,mijaj001,7,1,3,1,None,True
20,ANA201004080,craij001,8,1,6,1,None,True
21,ANA201004080,burna002,9,1,10,1,None,True
22,ANA201004090,bulgj001,6,0,5,2,None,False
23,ANA201004090,cassb001,7,0,10,2,None,False
24,ANA201004090,ramie003,7,1,10,2,None,True
25,ANA201004090,bresc001,9,1,10,4,None,True
26,ANA201004100,jepsk001,7,0,1,3,None,True
27,ANA201004100,shies002,8,0,2,3,None,True
28,ANA201004100,rodnf001,9,0,3,3,None,False
29,ANA201004100,blevj001,7,1,2,3,None,False
...,...,...,...,...,...,...,...,...
70,ANA201004250,rodnf001,8,0,4,8,None,True
71,ANA201004250,shies002,9,0,4,8,None,True
72,ANA201004250,logab001,4,1,3,5,None,False
73,ANA201004250,aceva001,5,1,3,5,None,False
74,ANA201004250,martd004,7,1,4,5,None,False
75,ANA201004250,mitrs001,8,1,4,8,None,False
76,ANA201004260,bulgj001,7,0,1,5,fuenb001,True
77,ANA201004260,jepsk001,7,0,1,5,fuenb001,True
78,ANA201004260,stokb001,8,0,1,5,fuenb001,True
79,ANA201004260,rodnf001,8,0,2,5,fuenb001,True
80,ANA201004260,fuenb001,9,0,2,5,fuenb001,True
81,ANA201004260,perer002,6,1,1,5,fuenb001,False
82,ANA201004260,sippt001,7,1,1,5,fuenb001,False
83,ANA201004270,palmm001,6,0,3,1,None,False
84,ANA201004270,shies002,8,0,7,1,None,False
85,ANA201004270,stokb001,9,0,8,1,None,False
86,ANA201004270,laffa001,7,1,4,1,None,True
87,ANA201004270,lewij003,8,1,8,1,None,True
88,ANA201004270,smitj002,8,1,8,1,None,True
89,ANA201004280,jepsk001,7,0,3,3,None,False
90,ANA201004280,rodnf001,8,0,3,3,None,False
91,ANA201004280,fuenb001,9,0,3,3,None,False
92,ANA201004280,wrigj001,7,1,3,3,None,False
93,ANA201004280,sippt001,8,1,3,3,None,False
94,ANA201004280,smitj002,9,1,3,3,None,False
95,ANA201004280,perer002,9,1,3,3,None,False
96,ANA201004280,perec002,9,1,3,3,None,False
97,ANA201005100,jepsk001,7,0,0,4,None,True
98,ANA201005100,rodnf001,8,0,0,4,None,True
99,ANA201005100,fuenb001,9,0,1,4,None,True

In [29]:
df_pitch_subs = df_pitch_subs[df_pitch_subs['SAVE_SIT'] == True].reindex()

In [30]:
df_pitch_subs[['GAME_ID', 'PIT_ID', 'INN_CT', 'BAT_HOME_ID', 'AWAY_SCORE_CT', 'HOME_SCORE_CT', 'SAVE_PIT_ID', 'SAVE_SIT']].head(10)

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,AWAY_SCORE_CT,HOME_SCORE_CT,SAVE_PIT_ID,SAVE_SIT
0,ANA201004050,jepsk001,7,0,3,4,fuenb001,True
1,ANA201004050,rodnf001,8,0,3,4,fuenb001,True
2,ANA201004050,fuenb001,9,0,3,6,fuenb001,True
8,ANA201004060,duenb001,7,1,5,3,raucj001,True
9,ANA201004060,guerm001,8,1,5,3,raucj001,True
10,ANA201004060,raucj001,9,1,5,3,raucj001,True
13,ANA201004070,guerm001,8,1,4,1,raucj001,True
14,ANA201004070,raucj001,9,1,4,1,raucj001,True
18,ANA201004080,neshp001,6,1,3,1,None,True
19,ANA201004080,mijaj001,7,1,3,1,None,True

In [31]:
df_next_pitcher = df_pitch_subs.shift(-1)
df_next_pitcher[['GAME_ID', 'PIT_ID', 'INN_CT', 'BAT_HOME_ID', 'AWAY_SCORE_CT', 'HOME_SCORE_CT', 'SAVE_PIT_ID', 'SAVE_SIT']].head(100)

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,AWAY_SCORE_CT,HOME_SCORE_CT,SAVE_PIT_ID,SAVE_SIT
0,ANA201004050,rodnf001,8.0,0.0,3.0,4.0,fuenb001,True
1,ANA201004050,fuenb001,9.0,0.0,3.0,6.0,fuenb001,True
2,ANA201004060,duenb001,7.0,1.0,5.0,3.0,raucj001,True
8,ANA201004060,guerm001,8.0,1.0,5.0,3.0,raucj001,True
9,ANA201004060,raucj001,9.0,1.0,5.0,3.0,raucj001,True
10,ANA201004070,guerm001,8.0,1.0,4.0,1.0,raucj001,True
13,ANA201004070,raucj001,9.0,1.0,4.0,1.0,raucj001,True
14,ANA201004080,neshp001,6.0,1.0,3.0,1.0,None,True
18,ANA201004080,mijaj001,7.0,1.0,3.0,1.0,None,True
19,ANA201004080,craij001,8.0,1.0,6.0,1.0,None,True
20,ANA201004080,burna002,9.0,1.0,10.0,1.0,None,True
21,ANA201004090,ramie003,7.0,1.0,10.0,2.0,None,True
24,ANA201004090,bresc001,9.0,1.0,10.0,4.0,None,True
25,ANA201004100,jepsk001,7.0,0.0,1.0,3.0,None,True
26,ANA201004100,shies002,8.0,0.0,2.0,3.0,None,True
27,ANA201004110,jepsk001,7.0,0.0,2.0,3.0,rosst001,True
32,ANA201004110,rosst001,7.0,1.0,4.0,3.0,rosst001,True
36,ANA201004190,jepsk001,8.0,0.0,0.0,2.0,rodnf001,True
37,ANA201004190,rodnf001,9.0,0.0,0.0,2.0,rodnf001,True
38,ANA201004200,bulgj001,6.0,0.0,0.0,6.0,rodnf001,True
40,ANA201004200,shies002,7.0,0.0,2.0,6.0,rodnf001,True
41,ANA201004200,palmm001,7.0,0.0,2.0,6.0,rodnf001,True
42,ANA201004200,jepsk001,8.0,0.0,5.0,6.0,rodnf001,True
43,ANA201004200,rodnf001,9.0,0.0,5.0,6.0,rodnf001,True
44,ANA201004210,bulgj001,8.0,0.0,2.0,3.0,valvj001,True
47,ANA201004210,fuenb001,9.0,0.0,2.0,3.0,valvj001,True
48,ANA201004210,valvj001,9.0,1.0,4.0,3.0,valvj001,True
52,ANA201004220,zumaj001,6.0,1.0,5.0,4.0,valvj001,True
56,ANA201004220,cokep001,7.0,1.0,5.0,4.0,valvj001,True
57,ANA201004220,perrr001,8.0,1.0,5.0,4.0,valvj001,True
...,...,...,...,...,...,...,...,...
156,ANA201006140,smitc002,9.0,1.0,12.0,2.0,None,True
157,ANA201006150,loe-k001,8.0,1.0,7.0,1.0,None,True
160,ANA201006150,axfoj001,9.0,1.0,7.0,1.0,None,True
161,ANA201006160,rodnf001,9.0,0.0,1.0,5.0,None,True
162,ANA201006220,rodnf001,8.0,0.0,3.0,6.0,fuenb001,True
167,ANA201006220,fuenb001,9.0,0.0,3.0,6.0,fuenb001,True
168,ANA201006230,jepsk001,8.0,0.0,1.0,2.0,fuenb001,True
171,ANA201006230,fuenb001,9.0,0.0,1.0,2.0,fuenb001,True
172,ANA201006240,tronr001,5.0,1.0,6.0,2.0,None,True
178,ANA201006240,weavj002,6.0,1.0,6.0,4.0,None,True
179,ANA201006240,kuo-h001,7.0,1.0,8.0,4.0,None,True
180,ANA201006240,millj002,8.0,1.0,10.0,4.0,None,True
181,ANA201006240,sherg001,9.0,1.0,10.0,5.0,None,True
182,ANA201006240,broxj001,9.0,1.0,10.0,6.0,None,True
183,ANA201006250,rodnf001,8.0,0.0,2.0,3.0,corpm001,True
184,ANA201006250,corpm001,11.0,1.0,4.0,3.0,corpm001,True
192,ANA201006260,rodnf001,8.0,0.0,2.0,4.0,fuenb001,True
193,ANA201006260,fuenb001,9.0,0.0,2.0,4.0,fuenb001,True
194,ANA201006270,shies002,7.0,0.0,3.0,5.0,None,True
195,ANA201006270,jepsk001,8.0,0.0,3.0,5.0,None,True
196,ANA201006270,rodrf005,9.0,0.0,3.0,10.0,None,True
197,ANA201006290,jepsk001,7.0,0.0,3.0,6.0,fuenb001,True
200,ANA201006290,rodnf001,8.0,0.0,5.0,6.0,fuenb001,True
201,ANA201006290,fuenb001,9.0,0.0,5.0,6.0,fuenb001,True
202,ANA201006300,nippd001,5.0,1.0,5.0,3.0,felin001,True
208,ANA201006300,franf001,8.0,1.0,6.0,4.0,felin001,True
209,ANA201006300,felin001,9.0,1.0,6.0,4.0,felin001,True
210,ANA201007010,rodnf001,8.0,0.0,0.0,2.0,fuenb001,True
211,ANA201007010,fuenb001,9.0,0.0,1.0,2.0,fuenb001,True
212,ANA201007020,fuenb001,9.0,0.0,0.0,1.0,sorij001,True

In [45]:
df_pitch_subs['made_save'] = None
df_pitch_subs.head()

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,OUTS_CT,AWAY_SCORE_CT,HOME_SCORE_CT,onFirst,onSecond,onThird,SAVE_PIT_ID,SAVE_SIT,made_save
0,ANA201004050,jepsk001,7,0,0,3,4,0,0,0,fuenb001,True,None
1,ANA201004050,rodnf001,8,0,0,3,4,0,0,0,fuenb001,True,None
2,ANA201004050,fuenb001,9,0,0,3,6,0,0,0,fuenb001,True,None
8,ANA201004060,duenb001,7,1,2,5,3,0,1,0,raucj001,True,None
9,ANA201004060,guerm001,8,1,0,5,3,0,0,0,raucj001,True,None

In [50]:
print(len(df_pitch_subs))
print(len(df_next_pitcher))
for t1, t2 in zip(df_pitch_subs.iterrows(), df_next_pitcher.iterrows()):
    cur_index = t1[0]
    cur_row = t1[1]
    next_row = t2[1]
    made_save = None
    
    if cur_row['GAME_ID'] == next_row['GAME_ID'] and cur_row['BAT_HOME_ID'] == next_row['BAT_HOME_ID']:
        # in same game, and same team.
        if cur_row['BAT_HOME_ID'] == 0:
            # home team
            blew_lead = next_row['HOME_SCORE_CT'] <= next_row['AWAY_SCORE_CT']
            if blew_lead:
                inn_diff = next_row['INN_CT'] - cur_row['INN_CT']
                init_score_diff = cur_row['HOME_SCORE_CT'] - cur_row['AWAY_SCORE_CT']
                
                if (init_score_diff <= 3 and inn_diff >= 1) or (inn_diff >= 3) or (cur_row['HOME_SCORE_CT'] <= cur_row['AWAY_SCORE_CT'] + 2 + sum([cur_row['onFirst'], cur_row['onSecond'], cur_row['onThird']])):
                    made_save = False
                
            
        elif cur_row['BAT_HOME_ID'] == 1:
            # away team
            blew_lead = next_row['HOME_SCORE_CT'] >= next_row['AWAY_SCORE_CT']
            if blew_lead:
                inn_diff = next_row['INN_CT'] - cur_row['INN_CT']
                init_score_diff = cur_row['AWAY_SCORE_CT'] - cur_row['HOME_SCORE_CT']
                
                if (init_score_diff <= 3 and inn_diff >= 1) or (inn_diff >= 3) or (cur_row['AWAY_SCORE_CT'] <= cur_row['HOME_SCORE_CT'] + 2 + sum([cur_row['onFirst'], cur_row['onSecond'], cur_row['onThird']])):
                    made_save = False
    
    
    elif cur_row['PIT_ID'] == cur_row['SAVE_PIT_ID']:
            made_save = True
               
    print
    if cur_index = 425:
        break
    df_pitch_subs.iloc[cur_index, df_pitch_subs.columns.get_loc('made_save')] = made_save
    
    
df_pitch_subs.head(50)

425
425
0
1
2
8
9
10
13
14
18
19
20
21
24
25
26
27
32
36
37
38
40
41
42
43
44
47
48
52
56
57
58
59
62
67
68
69
70
71
76
77
78
79
80
86
87
88
97
98
99
108
109
110
111
114
115
116
117
118
119
120
128
129
132
133
134
142
150
151
152
153
156
157
160
161
162
167
168
171
172
178
179
180
181
182
183
184
192
193
194
195
196
197
200
201
202
208
209
210
211
212
216
220
222
223
224
225
229
230
234
235
236
237
238
246
252
253
256
257
262
263
264
265
266
267
270
271
272
273
274
275
276
279
280
289
290
291
292
297
298
303
304
305
306
311
312
313
314
315
316
317
318
323
327
329
330
336
342
343
344
345
346
358
367
368
369
371
372
374
375
376
392
401
402
405
406
408
409
410
411
413
414
415
425
426
427
442
443
449
451
466
469
470
471
473
477
481
482
483
490
491
492
502
503
504
505
506
507
508
509
512
513
514
515
517
518
519
520
524
527
528
538
539
540
545
549
550
551
552
553
554
558
559
560
565
569
570
571
573
574
577
578
579
583
586
588
589
590
593
599
600
605
606
607
608
609
612
613
617
618
619
622
623
624
625
630
633
634
635
639
642
643
646
651
653
654
655
657
658
665
666
677
678
683
684
688
691
692
695
696
697
698
702
703
709
711
718
719
726
727
728
729
734
735
738
739
746
747
755
759
760
762
763
764
765
766
769
770
771
775
777
778
779
780
781
785
786
787
793
794
801
802
803
808
809
810
811
812
813
814
816
817
820
821
825
829
830
831
832
833
834
835
836
842
846
847
848
849
862
866
867
868
869
877
878
879
880
881
884
891
892
893
895
896
897
903
904
910
911
912
913
914
917
918
919
920
927
928
929
933
934
935
936
937
939
943
944
945
948
949
952
957
958
959
960
961
962
963
964
968
969
970
972
973
974
975
981
982
984
988
989
990
991
992
993
999

,GAME_ID,PIT_ID,INN_CT,BAT_HOME_ID,OUTS_CT,AWAY_SCORE_CT,HOME_SCORE_CT,onFirst,onSecond,onThird,SAVE_PIT_ID,SAVE_SIT,made_save
0,ANA201004050,jepsk001,7,0,0,3,4,0,0,0,fuenb001,True,None
1,ANA201004050,rodnf001,8,0,0,3,4,0,0,0,fuenb001,True,None
2,ANA201004050,fuenb001,9,0,0,3,6,0,0,0,fuenb001,True,True
8,ANA201004060,duenb001,7,1,2,5,3,0,1,0,raucj001,True,None
9,ANA201004060,guerm001,8,1,0,5,3,0,0,0,raucj001,True,None
10,ANA201004060,raucj001,9,1,0,5,3,0,0,0,raucj001,True,None
13,ANA201004070,guerm001,8,1,0,4,1,0,0,0,raucj001,True,None
14,ANA201004070,raucj001,9,1,0,4,1,0,0,0,raucj001,True,None
18,ANA201004080,neshp001,6,1,1,3,1,1,1,0,None,True,None
19,ANA201004080,mijaj001,7,1,0,3,1,0,0,0,None,True,None
20,ANA201004080,craij001,8,1,0,6,1,0,0,0,None,True,True
21,ANA201004080,burna002,9,1,0,10,1,0,0,0,None,True,None
24,ANA201004090,ramie003,7,1,0,10,2,0,1,0,None,True,None
25,ANA201004090,bresc001,9,1,1,10,4,1,0,0,None,True,None
26,ANA201004100,jepsk001,7,0,0,1,3,0,0,0,None,True,True
27,ANA201004100,shies002,8,0,0,2,3,0,0,0,None,True,None
32,ANA201004110,jepsk001,7,0,0,2,3,0,1,1,rosst001,True,None
36,ANA201004110,rosst001,7,1,0,4,3,0,0,0,rosst001,True,None
37,ANA201004190,jepsk001,8,0,1,0,2,1,1,0,rodnf001,True,None
38,ANA201004190,rodnf001,9,0,0,0,2,0,0,0,rodnf001,True,None
40,ANA201004200,bulgj001,6,0,2,0,6,1,1,0,rodnf001,True,None
41,ANA201004200,shies002,7,0,0,2,6,0,0,0,rodnf001,True,None
42,ANA201004200,palmm001,7,0,2,2,6,1,1,1,rodnf001,True,None
43,ANA201004200,jepsk001,8,0,0,5,6,0,0,0,rodnf001,True,None
44,ANA201004200,rodnf001,9,0,0,5,6,0,0,0,rodnf001,True,None
47,ANA201004210,bulgj001,8,0,0,2,3,0,0,0,valvj001,True,None
48,ANA201004210,fuenb001,9,0,0,2,3,0,0,0,valvj001,True,None
52,ANA201004210,valvj001,9,1,0,4,3,0,0,0,valvj001,True,None
56,ANA201004220,zumaj001,6,1,0,5,4,0,0,0,valvj001,True,None
57,ANA201004220,cokep001,7,1,2,5,4,0,0,1,valvj001,True,None
58,ANA201004220,perrr001,8,1,0,5,4,1,0,0,valvj001,True,None
59,ANA201004220,valvj001,9,1,0,5,4,0,0,0,valvj001,True,None
62,ANA201004230,fuenb001,9,0,0,4,6,0,0,0,fuenb001,True,None
67,ANA201004240,martd004,9,1,0,7,1,0,0,0,None,True,None
68,ANA201004250,bulgj001,6,0,1,4,5,0,0,0,None,True,None
69,ANA201004250,jepsk001,7,0,0,4,5,0,0,0,None,True,None
70,ANA201004250,rodnf001,8,0,0,4,8,0,0,0,None,True,True
71,ANA201004250,shies002,9,0,0,4,8,0,0,0,None,True,None
76,ANA201004260,bulgj001,7,0,0,1,5,0,0,0,fuenb001,True,True
77,ANA201004260,jepsk001,7,0,1,1,5,1,1,1,fuenb001,True,None
78,ANA201004260,stokb001,8,0,0,1,5,0,0,0,fuenb001,True,None
79,ANA201004260,rodnf001,8,0,1,2,5,1,0,0,fuenb001,True,None
80,ANA201004260,fuenb001,9,0,0,2,5,0,0,0,fuenb001,True,None
86,ANA201004270,laffa001,7,1,1,4,1,1,0,0,None,True,None
87,ANA201004270,lewij003,8,1,0,8,1,0,0,0,None,True,True
88,ANA201004270,smitj002,8,1,2,8,1,1,1,1,None,True,None
97,ANA201005100,jepsk001,7,0,1,0,4,1,1,0,None,True,None
98,ANA201005100,rodnf001,8,0,0,0,4,0,0,0,None,True,None
99,ANA201005100,fuenb001,9,0,0,1,4,0,0,0,None,True,None
108,ANA201005110,corml001,8,1,1,6,0,1,1,0,None,True,None